import os
import json

translations = {
    'en': {
        'activityLevel': 'How active are you?',
        'activityLevelSub': 'Select your daily activity level',
        'activitySedentary': 'Sedentary',
        'activitySedentarySub': 'Little or no exercise',
        'activityLight': 'Lightly Active',
        'activityLightSub': 'Light exercise 1-3 days/week',
        'activityActive': 'Active',
        'activityActiveSub': 'Moderate exercise 3-5 days/week',
        'activityVery': 'Very Active',
        'activityVerySub': 'Heavy exercise 6-7 days/week',
        'onboardingSummaryTitle': 'You\'re set! 🎉',
        'onboardingSummarySub': 'Here is your daily personalized goal.',
        'onboardingRecommend': 'Recommended Daily Calories',
        'onboardingGender': 'What is your gender?',
        'onboardingGenderSub': 'Used to calculate your metabolic rate.',
        'onboardingAge': 'How old are you?',
        'onboardingAgeSub': 'Used to calculate your metabolic rate.',
        'onboardingHeightWeight': 'Height & Weight',
        'onboardingHeightWeightSub': 'Required for BMI and daily calories.'
    },
    'tr': {
        'activityLevel': 'Ne kadar hareketlisin?',
        'activityLevelSub': 'Günlük aktivite seviyeni seç',
        'activitySedentary': 'Masa Başı',
        'activitySedentarySub': 'Çok az egzersiz veya ofis işi',
        'activityLight': 'Hafif Hareketli',
        'activityLightSub': 'Haftada 1-3 gün hafif egzersiz',
        'activityActive': 'Aktif',
        'activityActiveSub': 'Haftada 3-5 gün orta egzersiz',
        'activityVery': 'Çok Aktif',
        'activityVerySub': 'Haftada 6-7 gün ağır egzersiz',
        'onboardingSummaryTitle': 'Hazırsın! 🎉',
        'onboardingSummarySub': 'İşte sana özel günlük hedefin.',
        'onboardingRecommend': 'Önerilen Günlük Kalori',
        'onboardingGender': 'Cinsiyetin nedir?',
        'onboardingGenderSub': 'Metabolizma hızını hesaplamak için gerekli.',
        'onboardingAge': 'Kaç yaşındasın?',
        'onboardingAgeSub': 'Metabolizma hızını hesaplamak için gerekli.',
        'onboardingHeightWeight': 'Boy ve Kilo',
        'onboardingHeightWeightSub': 'VKI ve günlük kalori ihtiyacın için gerekli.'
    },
    'de': {
        'activityLevel': 'Wie aktiv bist du?',
        'activityLevelSub': 'Wähle dein tägliches Aktivitätslevel',
        'activitySedentary': 'Sitzend',
        'activitySedentarySub': 'Kaum oder keine Bewegung',
        'activityLight': 'Leicht aktiv',
        'activityLightSub': '1-3 Tage/Woche leichtes Training',
        'activityActive': 'Aktiv',
        'activityActiveSub': '3-5 Tage/Woche moderates Training',
        'activityVery': 'Sehr aktiv',
        'activityVerySub': '6-7 Tage/Woche hartes Training',
        'onboardingSummaryTitle': 'Fertig! 🎉',
        'onboardingSummarySub': 'Hier ist dein tägliches Ziel.',
        'onboardingRecommend': 'Empfohlene tägliche Kalorien',
        'onboardingGender': 'Was ist dein Geschlecht?',
        'onboardingGenderSub': 'Wird zur Berechnung der Stoffwechselrate benötigt.',
        'onboardingAge': 'Wie alt bist du?',
        'onboardingAgeSub': 'Wird zur Berechnung der Stoffwechselrate benötigt.',
        'onboardingHeightWeight': 'Größe & Gewicht',
        'onboardingHeightWeightSub': 'Erforderlich für den BMI und tägliche Kalorien.'
    },
    'fr': {
        'activityLevel': 'Quel est ton niveau d\'activité ?',
        'activityLevelSub': 'Choisis ton niveau d\'activité quotidien',
        'activitySedentary': 'Sédentaire',
        'activitySedentarySub': 'Peu ou pas d\'exercice',
        'activityLight': 'Légèrement actif',
        'activityLightSub': 'Exercice léger 1-3 jours/semaine',
        'activityActive': 'Actif',
        'activityActiveSub': 'Exercice modéré 3-5 jours/semaine',
        'activityVery': 'Très actif',
        'activityVerySub': 'Exercice intense 6-7 jours/semaine',
        'onboardingSummaryTitle': 'C\'est parti ! 🎉',
        'onboardingSummarySub': 'Voici ton objectif quotidien personnalisé.',
        'onboardingRecommend': 'Calories quotidiennes recommandées',
        'onboardingGender': 'Quel est ton sexe ?',
        'onboardingGenderSub': 'Utilisé pour calculer ton métabolisme.',
        'onboardingAge': 'Quel âge as-tu ?',
        'onboardingAgeSub': 'Utilisé pour calculer ton métabolisme.',
        'onboardingHeightWeight': 'Taille et Poids',
        'onboardingHeightWeightSub': 'Requis pour l\'IMC et les calories.'
    },
    'es': {
        'activityLevel': '¿Qué tan activo eres?',
        'activityLevelSub': 'Selecciona tu nivel de actividad diaria',
        'activitySedentary': 'Sedentario',
        'activitySedentarySub': 'Poco o ningún ejercicio',
        'activityLight': 'Ligeramente activo',
        'activityLightSub': 'Ejercicio ligero 1-3 días/semana',
        'activityActive': 'Activo',
        'activityActiveSub': 'Ejercicio moderado 3-5 días/semana',
        'activityVery': 'Muy activo',
        'activityVerySub': 'Ejercicio intenso 6-7 días/semana',
        'onboardingSummaryTitle': '¡Listo! 🎉',
        'onboardingSummarySub': 'Aquí está tu objetivo diario personalizado.',
        'onboardingRecommend': 'Calorías diarias recomendadas',
        'onboardingGender': '¿Cuál es tu género?',
        'onboardingGenderSub': 'Usado para calcular tu metabolismo.',
        'onboardingAge': '¿Cuántos años tienes?',
        'onboardingAgeSub': 'Usado para calcular tu metabolismo.',
        'onboardingHeightWeight': 'Altura y Peso',
        'onboardingHeightWeightSub': 'Necesario para el IMC y calorías.'
    },
    'ar': {
        "activityLevel": "ما مدى نشاطك؟",
        "activityLevelSub": "حدد مستوى نشاطك اليومي",
        "activitySedentary": "خامل",
        "activitySedentarySub": "تمرين قليل أو معدوم",
        "activityLight": "نشط قليلاً",
        "activityLightSub": "تمرين خفيف 1-3 أيام/أسبوع",
        "activityActive": "نشط",
        "activityActiveSub": "تمرين معتدل 3-5 أيام/أسبوع",
        "activityVery": "نشيط جدا",
        "activityVerySub": "تمرين شاق 6-7 أيام/أسبوع",
        "onboardingSummaryTitle": "أنت مستعد! 🎉",
        "onboardingSummarySub": "إليك هدفك اليومي المخصص.",
        "onboardingRecommend": "السعرات الحرارية اليومية الموصى بها",
        "onboardingGender": "ما هو جنسك؟",
        "onboardingGenderSub": "يستخدم لحساب معدل الأيض الخاص بك.",
        "onboardingAge": "كم عمرك؟",
        "onboardingAgeSub": "يستخدم لحساب معدل الأيض الخاص بك.",
        "onboardingHeightWeight": "الطول والوزن",
        "onboardingHeightWeightSub": "مطلوب لتحديد مؤشر كتلة الجسم والسعرات."
    },
    'pt': {
        'activityLevel': 'Quão ativo você é?',
        'activityLevelSub': 'Selecione seu nível de atividade diária',
        'activitySedentary': 'Sedentário',
        'activitySedentarySub': 'Pouco ou nenhum exercício',
        'activityLight': 'Levemente ativo',
        'activityLightSub': 'Exercício leve 1-3 dias/semana',
        'activityActive': 'Ativo',
        'activityActiveSub': 'Exercício moderado 3-5 dias/semana',
        'activityVery': 'Muito ativo',
        'activityVerySub': 'Exercício intenso 6-7 dias/semana',
        'onboardingSummaryTitle': 'Tudo pronto! 🎉',
        'onboardingSummarySub': 'Aqui está o seu objetivo diário personalizado.',
        'onboardingRecommend': 'Calorias diárias recomendadas',
        'onboardingGender': 'Qual é o seu gênero?',
        'onboardingGenderSub': 'Usado para calcular sua taxa metabólica.',
        'onboardingAge': 'Qual a sua idade?',
        'onboardingAgeSub': 'Usado para calcular sua taxa metabólica.',
        'onboardingHeightWeight': 'Altura e Peso',
        'onboardingHeightWeightSub': 'Necessário para cálculos de IMC e calorias.'
    },
    'ru': {
        "activityLevel": "Насколько вы активны?",
        "activityLevelSub": "Выберите ваш ежедневный уровень активности",
        "activitySedentary": "Скромный",
        "activitySedentarySub": "Мало или совсем без упражнений",
        "activityLight": "Слегка активный",
        "activityLightSub": "Легкие упражнения 1-3 дня/нед",
        "activityActive": "Активный",
        "activityActiveSub": "Умеренные упражнения 3-5 дней/нед",
        "activityVery": "Очень активный",
        "activityVerySub": "Тяжелые упражнения 6-7 дней/нед",
        "onboardingSummaryTitle": "Вы готовы! 🎉",
        "onboardingSummarySub": "Вот ваша персональная ежедневная цель.",
        "onboardingRecommend": "Рекомендуемые ежедневные калории",
        "onboardingGender": "Каков ваш пол?",
        "onboardingGenderSub": "Используется для расчета обмена веществ.",
        "onboardingAge": "Сколько вам лет?",
        "onboardingAgeSub": "Используется для расчета обмена веществ.",
        "onboardingHeightWeight": "Рост и Вес",
        "onboardingHeightWeightSub": "Необходимо для ИМТ и калорий."
    },
    'it': {
        'activityLevel': 'Quanto sei attivo?',
        'activityLevelSub': 'Seleziona il tuo livello di attività quotidiana',
        'activitySedentary': 'Sedentario',
        'activitySedentarySub': 'Poco o nessun esercizio',
        'activityLight': 'Leggermente attivo',
        'activityLightSub': 'Esercizio leggero 1-3 giorni/settimana',
        'activityActive': 'Attivo',
        'activityActiveSub': 'Esercizio moderato 3-5 giorni/settimana',
        'activityVery': 'Molto attivo',
        'activityVerySub': 'Esercizio intenso 6-7 giorni/settimana',
        'onboardingSummaryTitle': 'Ci sei quasi! 🎉',
        'onboardingSummarySub': 'Ecco il tuo obiettivo giornaliero personalizzato.',
        'onboardingRecommend': 'Calorie giornaliere raccomandate',
        'onboardingGender': 'Qual è il tuo sesso?',
        'onboardingGenderSub': 'Usato per calcolare il tuo metabolismo.',
        'onboardingAge': 'Quanti anni hai?',
        'onboardingAgeSub': 'Usato per calcolare il tuo metabolismo.',
        'onboardingHeightWeight': 'Altezza e Peso',
        'onboardingHeightWeightSub': 'Necessario per BMI e calorie.'
    },
    'ka': {
        "activityLevel": "რამდენად აქტიური ხართ?",
        "activityLevelSub": "აირჩიეთ ყოველდღიური აქტივობის დონე",
        "activitySedentary": "მჯდომარე",
        "activitySedentarySub": "მცირე ან ვარჯიშის გარეშე",
        "activityLight": "მსუბუქი აქტიური",
        "activityLightSub": "მსუბუქი ვარჯიში 1-3 დღე/კვირა",
        "activityActive": "აქტიური",
        "activityActiveSub": "საშუალო ვარჯიში 3-5 დღე/კვირა",
        "activityVery": "ძალიან აქტიური",
        "activityVerySub": "მძიმე ვარჯიში 6-7 დღე/კვირა",
        "onboardingSummaryTitle": "თქვენ მზად ხართ! 🎉",
        "onboardingSummarySub": "აქ არის თქვენი პერსონალური ყოველდღიური მიზანი.",
        "onboardingRecommend": "რეკომენდებული ყოველდღიური კალორიები",
        "onboardingGender": "რა სქესის ხართ?",
        "onboardingGenderSub": "გამოიყენება მეტაბოლიზმის სიჩქარის გამოსათვლელად.",
        "onboardingAge": "რამდენი წლის ხართ?",
        "onboardingAgeSub": "გამოიყენება მეტაბოლიზმის სიჩქარის გამოსათვლელად.",
        "onboardingHeightWeight": "სიმაღლე და წონა",
        "onboardingHeightWeightSub": "საჭიროა BMI და კალორიებისთვის."
    }
}

l10n_dir = 'lib/l10n'

for lang, trans in translations.items():
    file_path = os.path.join(l10n_dir, f'app_{lang}.arb')
    if not os.path.exists(file_path): continue
    
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    for k, v in trans.items():
        data[k] = v
    
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("ARB files updated successfully for Task E.")
